---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2017 Ericsson AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- name: ensure glean rules are removed
  file:
    path: "/etc/udev/rules.d/99-glean.rules"
    state: absent

- block:
    - name: configure modules
      lineinfile:
        dest: /etc/modules
        state: present
        create: yes
        line: "8021q"
    - name: add modules
      modprobe:
        name: 8021q
        state: present
    - name: ensure interfaces.d folder is empty
      shell: "/bin/rm -rf /etc/network/interfaces.d/*"
    - name: ensure interfaces file is updated
      template:
        src: "{{ ansible_os_family | lower }}/{{ ansible_hostname }}.interface.j2"
        dest: "/etc/network/interfaces"
    - name: restart network service
      shell: "/sbin/ifconfig {{ ansible_default_ipv4.interface }} 0 && /sbin/ifdown -a && /sbin/ifup -a"
  when: ansible_os_family | lower == "debian"

- block:
    - name: Remove existing network configuration
      file:
        path: "/etc/sysconfig/network/{{ item }}"
        state: absent
      with_items:
        - "ifcfg-eth0"
        - "ifroute-eth0"

    - name: Configure networking on SUSE
      template:
        src: "{{ ansible_os_family | lower }}/suse.interface.j2"
        dest: "/etc/sysconfig/network/ifcfg-{{ item.name }}"
      with_items:
        - { name: "{{ ansible_default_ipv4.interface }}" }
        - { name: "{{ ansible_default_ipv4.interface }}.10", vlan_id: 10 }
        - { name: "{{ ansible_default_ipv4.interface }}.30", vlan_id: 30 }
        - { name: "{{ ansible_default_ipv4.interface }}.20", vlan_id: 20 }
        - { name: "br_mgmt", bridge_ports: "{{ ansible_default_ipv4.interface }}.10", ip: "{{ host_info[inventory_hostname].MGMT_IP }}/22" }
        - { name: "br_vxlan", bridge_ports: "{{ ansible_default_ipv4.interface }}.30", ip: "{{ host_info[inventory_hostname].VXLAN_IP }}/22" }
        - { name: "br_vlan", bridge_ports: "{{ ansible_default_ipv4.interface }}", ip: "{{ host_info[inventory_hostname].VLAN_IP }}/24" }
        - { name: "br_storage", bridge_ports: "{{ ansible_default_ipv4.interface }}.20", ip: "{{ host_info[inventory_hostname].STORAGE_IP }}/22" }

    - name: Add postup/postdown scripts on SUSE
      copy:
        src: "network-config-suse"
        dest: "/etc/sysconfig/network/scripts/network-config-suse"
        mode: 0755

    - name: Configure routes on SUSE
      template:
        src: "{{ ansible_os_family | lower }}/suse.routes.j2"
        dest: "/etc/sysconfig/network/ifroute-{{ item.name }}"
      with_items:
        - { name: "br_vlan", gateway: "192.168.122.1", route: "default" }

    - name: restart network service
      shell: "/usr/sbin/wicked ifreload all"
  when: ansible_os_family | lower == "suse"

- block:
    - name: Configure networking on CentOS for interfaces
      template:
        src: "{{ ansible_os_family | lower }}/interface.ifcfg.j2"
        dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.name }}"
      with_items:
        - { name: "{{ ansible_default_ipv4.interface }}"   , bridge: "br_vlan"                 }
        - { name: "{{ ansible_default_ipv4.interface }}.10", bridge: "br_mgmt"   , vlan_id: 10 }
        - { name: "{{ ansible_default_ipv4.interface }}.20", bridge: "br_storage", vlan_id: 20 }
        - { name: "{{ ansible_default_ipv4.interface }}.30", bridge: "br_vxlan"  , vlan_id: 30 }
    - name: Configure networking on CentOS for bridges
      template:
        src: "{{ ansible_os_family | lower }}/bridge.ifcfg.j2"
        dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.name }}"
      with_items:
        - { name: "br_vlan"   , ip: "{{ host_info[inventory_hostname].VLAN_IP }}",    prefix: 24 }
        - { name: "br_mgmt"   , ip: "{{ host_info[inventory_hostname].MGMT_IP }}",    prefix: 22 }
        - { name: "br_storage", ip: "{{ host_info[inventory_hostname].STORAGE_IP }}", prefix: 22 }
        - { name: "br_vxlan"  , ip: "{{ host_info[inventory_hostname].VXLAN_IP }}",   prefix: 22 }
    - name: Add default route through br_vlan
      lineinfile:
        path: "/etc/sysconfig/network-scripts/ifcfg-br_vlan"
        line: "GATEWAY=192.168.122.1"
    - name: Restart networking
      command: "systemctl restart network"
    - name: wait for the server to come back
      wait_for_connection:
  when: ansible_os_family | lower == "redhat"
