---
# vars file for prepare_jumphost

xci_images: "{{ xci_root }}/images"
xci_configs_root: "{{ xci_root }}/etc"
xci_venv_root: "{{ xci_root }}/venv"
xci_src_root: "{{ xci_root }}/src"
xci_log_root: "{{ xci_root }}/log"
xci_bin_root: "{{ xci_root }}/bin"

home: "/home/{{ user }}"
ssh_certs_folder: "{{ lookup('env','HOME') }}/.ssh"
